### ISSUE TITLE
Incorrectly specified paths for <video poster>

### ISSUE THREAD

**Issue by arestov-work** [ixkaito/astro-relative-links#10]
When building a project ("astro build"), astro specifies the wrong path for <video poster>, how can this be corrected?
![1](https://github.com/ixkaito/astro-relative-links/assets/127933111/a9c1e78a-040b-4368-bd71-ed307632da55)
This is the way we have indicated

![2](https://github.com/ixkaito/astro-relative-links/assets/127933111/53ff79ae-a8f5-42f7-bf3e-c8e78708fb66)
and thats the one we get after compiling files in "dist" directory

![3](https://github.com/ixkaito/astro-relative-links/assets/127933111/a493c359-32dd-460d-882e-c6a5be91a091)
and that is the way we supposed to get, but we had to fix it manualy

What to do?

**Comment by ixkaito** [comment]
@arestov-work Thank you for your report! I'll fix this.

**Comment by ixkaito** [comment]
@arestov-work Fixed this bug in v0.3.6. Please try it.
