### ISSUE TITLE
Does not work at all on very simple windows setup.

### ISSUE THREAD

**Issue by breuxi** [ixkaito/astro-relative-links#11]
Hello! First of all thank you very much for creating this package.
Sadly it does not work at all out of the box on my current setup.

OS: Windows 10
Package Versions:
- `astro@4.0.6`
- `astro-relative-links@0.3.5`

I am also using the build format 'file' in my config (but it also does not work without).

It seems like it ignores the files in the root directory because of the glob syntax in

https://github.com/ixkaito/astro-relative-links/blob/2b4c83c69438cf0fbe992ae908542adcccac5a00/src/index.ts#L96C69-L96C69

When I add a slash in front of the two asterisks, it works again, which might be caused by windows path handling? Maybe I am missing something, but I wanted to let you know!

Thanks again and have a nice day,
Breuxi

**Comment by ixkaito** [comment]
@breuxi Thank you for your report! I'll check it.

**Comment by ixkaito** [comment]
@breuxi Fixed in [v0.3.7](https://github.com/ixkaito/astro-relative-links/releases/tag/v0.3.7).

Related: #8

Again, thank you for your report.

**Comment by breuxi** [comment]
Thank YOU for the fix! :D
