### ISSUE TITLE
astro dev support

### ISSUE THREAD

**Issue by nlvw** [ixkaito/astro-relative-links#13]
Is it possible to get this to work with `astro dev`?

I use a project called [code-server](https://github.com/coder/code-server) which proxies ports through a '/proxy/portnumber' url.  So when running the url of the homepage would look something like http://localhost:4080/proxy/4321/.  Since the proxy port can change relative paths are needed.

This project works fine when doing `astro build` then `astro preview`, however `astro dev` doesn't work at all.  All of the asset's ignore the relative paths ans use absolute paths such as  http://localhost:4080/node_modules when it should be http://localhost:4080/proxy/4321/node_modules

**Comment by wendevlin** [comment]
Hello,

I think a base path should help you:
https://docs.astro.build/en/reference/configuration-reference/#base

**Comment by ixkaito** [comment]
Thanks @wendevlin !

@nlvw I also think the `base` config should help you.

Please check the "[With `base` config](https://github.com/ixkaito/astro-relative-links?tab=readme-ov-file#with-base-config)" section in the README.
