### ISSUE TITLE
should not directly depend on `astro`

### ISSUE THREAD

**Issue by mayank99** [ixkaito/astro-relative-links#14]
I think `astro` should be a peer dependency, not a directly dependency as declared here:

https://github.com/ixkaito/astro-relative-links/blob/af411b591b778c76df8abb22e6a2ff15715a84c2/package.json#L34-L35

The user of this integration will already have installed `astro` (and probably a different version too).

**Comment by ixkaito** [comment]
@mayank99 Thanks! Fixed.
