### ISSUE TITLE
Add support for Astro v5

### ISSUE THREAD

**Issue by davidsandoz** [ixkaito/astro-relative-links#20]
Astro v5 got released yesterday. astro-relative-links has Astro v3 and v4 as peer dependency. Therefore, we cannot update to Astro v5 if we have astro-relative-links in the same project.

Would it be possible to make astro-relative-links compatible with Astro v5, please?

**Comment by hirasso** [comment]
It's working fine for me! Even with the older peerDependency. Also, just wanted to say: THANK YOU @ixkaito for this integration, it just saved me a major headache ❤️

**Comment by ixkaito** [comment]
@davidsandoz Thank you for your report! #19 fixed this issue.
