### ISSUE TITLE
strange link to resourses generated

### ISSUE THREAD

**Issue by stormitornado** [ixkaito/astro-relative-links#3]
Hi, thanks for plugin
But sadly, it didn't work for me.

When I built project, link to all of the resourses was rewritten this way:
```
url(..\..\..\..\..\..\D:\openserver\domains\hr-academy\dist/assets/fonts/fa-brands-400.woff2)
<link rel="stylesheet" href="..\..\..\..\D:\openserver\domains\hr-academy\dist/assets/css/common.css" />
```
and so on

Astro version - 2.1.2
OS - Windows 10

I didn't set `base` option, but I have custom `assetFileNames ` function, which rewrite some assets paths.
What could be a reason for this?

**Comment by ixkaito** [comment]
@stormitornado Thanks for the report. I think it's because Windows handles paths differently than Unix and macOS. Please give me a few days to fix it.

**Comment by ixkaito** [comment]
Hi @stormitornado. Just released v0.3.1, and it fixes bugs on Windows. Could you please give it a try? If it doesn't work, please reopen this issue.

**Comment by stormitornado** [comment]
yes, it mostly work, but not with styles.
two examples:

![image](https://user-images.githubusercontent.com/29771000/228820445-061db084-5409-4742-864e-606d3d9f9288.png)
<img width="449" alt="image" src="https://user-images.githubusercontent.com/29771000/228820575-e3a4888b-7971-4693-b09f-008d95f25a51.png">

First one is css-file, generated from separated scss-file, which was imported in layout.astro (these are common styles).
Second one - just inline style, where url was taken from img import: `import head_bg from "../images/header-bg.jpg"`

**Comment by ixkaito** [comment]
@stormitornado Thanks! I see. I have to resolve backslashes in Windows paths, and I forgot about the inline style.

**Comment by ixkaito** [comment]
@stormitornado I fixed the backslash problem on Windows and added support for `url()` in HTML inline style. Please test the latest [v0.3.2](https://github.com/ixkaito/astro-relative-links/releases/tag/v0.3.2) release.

**Comment by stormitornado** [comment]
yeah, thanks, it's working now, and it could be perfect if paths were really relative )
now in css we go to the top level and then - to target
`url(../../assets/fonts/fa-brands-400.woff2)`
it's also working but would be better like this (all these files are inside assets):
`url(../fonts/fa-brands-400.woff2`
of couse if it's possible and you have time for this

**Comment by ixkaito** [comment]
@stormitornado Thank you for testing.

> now in css we go to the top level and then - to target

Yes, I've noticed this issue. It's possible to solve it, but the implementation would be complicated and there'll be a risk of more bugs. If it works fine now, I would keep the current simple implementation.
