### ISSUE TITLE
Doesn't seem to work with Island Components

### ISSUE THREAD

**Issue by phocks** [ixkaito/astro-relative-links#5]
Still has absolute links on Components from frameworks. Up top is fine, but down the bottom with the framework components we have a problem.

<img width="1702" alt="Screen Shot 2023-04-21 at 4 29 06 pm" src="https://user-images.githubusercontent.com/437566/233557962-e3159762-2b2d-4ba4-bb61-4b8cab3add10.png">

**Comment by ixkaito** [comment]
Now supported in [v0.3.4](https://github.com/ixkaito/astro-relative-links/releases/tag/v0.3.4).

@phocks Thank you for your report.

@davidsandoz Thank you for your contirbution.
