### ISSUE TITLE
Relative link not work in few scenarios

### ISSUE THREAD

**Issue by yagee** [ixkaito/astro-relative-links#9]
Hi there!

Thank you again for this wonderful plugin!

I got these two cases, when `astro-relative-links` actually won't work:

1. In embedded `<styles>`
2. In script URL's

1:
![image](https://github.com/ixkaito/astro-relative-links/assets/1481199/c7d3d24d-c76f-427d-88df-b658779dba25)
![image](https://github.com/ixkaito/astro-relative-links/assets/1481199/2ec16f9d-f1d6-4c62-90d4-9b482e4b1828)

2:
![image](https://github.com/ixkaito/astro-relative-links/assets/1481199/4f85b26d-e758-41e1-9f55-828b27fc71ce)
![image](https://github.com/ixkaito/astro-relative-links/assets/1481199/eeaeb530-ad5d-4518-a7a0-c5f66ff4f2a6)

I made this stackblitz example: https://stackblitz.com/edit/withastro-astro-z6nzxi?file=dist%2Findex.html

Just run  `pnpm i` and `pnpm build` in terminal, and in both html files (`dist/index.html` and `dist/01/index.html`) you can see there are no changes in URL's to font and to pictures.

Is it possible to make this work?

Thank you!

**Comment by ixkaito** [comment]
@yagee Thank you for your report. I'll take a look.

**Comment by bnjmnrsh** [comment]
I could really use this as well for a project Im currently on - is there a blocking issue? What needs to be done? I could submit a PR.

**Comment by Kellytom** [comment]
> I could really use this as well for a project Im currently on - is there a blocking issue? What needs to be done? I could submit a PR.

Maybe Try ngrok if u need a solution now.

**Comment by ixkaito** [comment]
I'm sorry, everyone. I'm really busy with my client work. I think I'll be able to offer some solutions this weekend.

**Comment by ixkaito** [comment]
I released [v4.0](https://github.com/ixkaito/astro-relative-links/releases/tag/v4.0) to add support for embedded `<style>`. However, the second case is very difficult. While it is possible to support this, there is a risk of unintended replacements occurring in other areas as well.

**Comment by yagee** [comment]
Thanks @ixkaito !
I think this issue is solved, second case really rare.
